  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: first-springboot
    name: first-springboot
    namespace: default
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: first-springboot
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: first-springboot
      spec:
        containers:
        - image: vynaidudocker/hello-world-rest-api:0.0.4-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: hello-world-rest-api
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: first-springboot
    name: first-springboot
    namespace: default
  spec:
    ports:
    - nodePort: 30547
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: first-springboot
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 34.123.92.157