  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: todo-web-app
    name: todo-web-app
    namespace: default
  spec:
    replicas: 2
    minReadySeconds: 45
    selector:
      matchLabels:
        app: todo-web-app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: todo-web-app
      spec:
        containers:
        - image: vynaidudocker/todo-web-application-h2:0.0.1
          imagePullPolicy: IfNotPresent
          name: todo-web-application-h2
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
---
  apiVersion: v1
  kind: Service
  metadata:
    labels: #PODS
      app: todo-web-app
    name: todo-web-app
    namespace: default
  spec:
    ports:
    - nodePort: 30547
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: todo-web-app
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 34.123.92.157